name: Home Assistant Git Exporter
version: 0.1.10
slug: git-exporter
description: Export all of your Home Assistant configuration to a git repository of your choice
url: https://github.com/matt-richardson/home-assistant-git-exporter-addon
arch:
  - aarch64
  - amd64
startup: once
boot: manual
init: false
hassio_api: true
# manager role is required for bashio::addons.installed and bashio::addon.options
# used by export.addons. If you disable that export, default role would suffice.
hassio_role: manager
map:
  - type: config
    read_only: true
  - type: all_addon_configs
    read_only: true
options:
  repository:
    url: ''
    username: ''
    password: ''
    pull_before_push: true
    commit_message: Home Assistant Git Exporter {DATE}
    branch_name: main
  export:
    lovelace: true
    addons: true
    addon_configs: true
    esphome: true
    node_red: true
  check:
    enabled: true
    check_for_secrets: true
    check_for_ips: true
    redact_ips: true
  exclude:
    - '*.db'
    - '*.log*'
    - __pycache__
    - ._*
    - .DS_Store
    - deps/
    - known_devices.yaml
    - tts/
    - '*.db-shm'
    - '*.db-wal'
    - '*.gz'
  dry_run: false
schema:
  repository:
    url: match(https://.*)
    email: match(.+@.+)?
    username: str
    password: password
    pull_before_push: bool
    commit_message: str
    branch_name: str
    ssl_verification: bool?
  export:
    lovelace: bool
    addons: bool
    addon_configs: bool
    esphome: bool
    node_red: bool
  check:
    enabled: bool
    check_for_secrets: bool
    check_for_ips: bool
    redact_ips: bool
  exclude:
    - str
  dry_run: bool
